name: cmake CI

on:
  push:
    branches: [ "cmake" ]
  pull_request:
    branches: [ "cmake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: |
        sudo apt update
        sudo apt install liblibevent-dev -y
        sudo apt install liblibevent-dev -y
        rm -rf build
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug